### ISSUE TITLE
이름 입력 후 오류

### ISSUE THREAD

**Issue by fsanchir** [Team-Fi/mud-game#1]
------------------------------------------------------------------------------------------------------------------------
Fi의 말:
동방성련선

이름을 입력해주세요:
                                                                                                     BGM. スタッフロール['Director\n', '  Takao Unno\n', '\n', 'Planning Director\n', '  Masafumi Saito\n', '\n', 'Program Director\n', '  Sosuke Tamada\n', '\n', 'Art Director\n', '  Takao Unno\n', '\n', 'Scenario\n', '  Toshinobu Matsumiya\n', '\n', 'Programming\n', '  Akito Mori (Lead)\n', '  Miyuki Iwasawa\n', '  Toru Nagihashi\n', '  Katsuhiko Ichiraku\n', '  Masayuki Onoue\n', '  Ryouta Tanaka\n', '\n', 'Pokemon Black and White Version Programming\n', '  Tetsuya Watanabe\n', '  Hisashi Sogabe\n', '  Katsumi Ohno\n', '  Masao Taya\n', '  Hiroyuki Nakamura\n', '  Nozomu Saito\n', '  Tomoya Takahashi\n', '  Genya Hosaka\n', '  Nobuhiko Ariizumi\n', '  Toshihiro Obata\n', '  Koji Kawada\n', '  Yoshinori Matsuda\n', '  Keita Kagaya\n', '\n', 'Director of Pokemon Characters\n', '  Ken Sugimori\n', '\n', 'Pokemon Character Design\n', '  Ken Sugimori\n', '  Takao Unno\n', '  Motofumi Fujiwara\n', '  Hironobu Yoshida\n', '  Kenkichi Toyama\n', '  Hiroki Fuchino\n', '  Yusuke Ohmura\n', '  Saya Tsuruta\n', '  Lee HyunJung\n', '  Mana Ibe\n', '  Reiko Tanoue\n', '  Maiko Fujiwara\n', '  Megumi Mizutani\n', '  Tomuhiko Ohkubo\n', '  James Turner\n', '  Atsuko Nishida\n', '  Keiko Moritsugu\n', '  Tomohiro Kitakaze\n', '\n', '2-D Dot Graphics\n', '  Hironobu Yoshida (Lead)\n', '  Kenkichi Toyama\n', '  Saya Tsuruta\n', '  Megumi Mizutani\n', '  Yusuke Ohmura\n', '\n', '3-D Map Graphics\n', '  Tomohiko Ohkubo (Lead)\n', '  Hiroki Fuchino\n', '  Mana Ibe\n', '  Mayo Ohtani\n', '  Yuki Kawamuto\n', '  Motofumi Fujiwara\n', '  Tsubasa Matsuzaki\n', '  Yukiko Shiiyama\n', '  Yuichiro Takao\n', '  Atsushi Watanabe\n', '\n', 'Trainer Graphics--Main Design\n', '  Yusuke Ohmura\n', '\n', 'Trainer Graphics Design\n', '  Mana Ibe\n', '  Megumi Mizutani\n', '\n', 'Battle Graphics Design\n', '  Hironobu Yoshida\n', '\n', 'Battle Effect Design\n', '  Motofumi Fujiwara\n', '\n', 'User Interface Graphics--Main Design\n', '  Kenkichi Toyama\n', '\n', 'Digital Movie--Main Design\n', '  Takao Unno\n', '\n', 'Pokemon Black and White Version Graphics Design\n', '  Lee HyunJung\n', '  Reiko Tanoue\n', '  Maiko Fujiwara\n', '  James Turner\n', '  Keiko Moritsugu\n', '  Tomohiro Kitakaze\n', '\n', 'Pokemon Concept & Pokedex Text\n', '  Toshinobu Matsumiya\n', '\n', 'Music\n', '  Go Ichinose\n', '  Hitomi Sato\n', '\n', 'Pokemon Voice Design\n', '  Go Ichinose\n', '\n', 'Sound Effects\n', '  Hitomi Sato\n', '  Teruo Taniguchi\n', '\n', 'Music--Humilau City, Route 23 and more music\n', '  Go Ichinose\n', '\n', 'Music--Route 19, Join Avenue and more music\n', '  Hitomi Sato\n', '\n', 'Pokemon Black and White Version Music\n', '  Junichi Masuda\n', '  Shota Kageyama\n', '  Minako Adachi\n', '\n', 'Game Design\n', '  Teruyuki Shimoyamada (Lead)\n', '  Suguru Nakatsui (Lead)\n', '  Toshinobu Matsumiya (Lead)\n', '  Koji Nishino\n', '  Mai Mizuguchi\n', '  Katsunori Suginaka\n', '  Akira Nakamura\n', '  Hiroto Ito\n', '  Naoto Murakami\n', '\n', 'Text\n', '  Toshinobu Matsumiya\n', '  Suguru Nakatsui\n', '  Hiroto Ito\n', '  Hikaru Yoshikawa\n', '\n', 'Action Script\n', '  Mai Mizuguchi\n', '  Katsunori Suginaka\n', '  Soichiro Fujimura\n', '\n', 'Map Design\n', '  Suguru Nakatsui\n', '  Katsunori Suginaka\n', '  Akira Nakamura\n', '  Koji Nishino\n', '  Yohei Asaoka\n', '  Kazuki Muroi\n', '\n', 'Parameter Setting\n', '  Koji Nishino\n', '  Hiroto Ito\n', '\n', 'Pokestar Studios Design\n', '  Suguru Nakatsui\n', '  Pokemon World Tournament Design\n', '  Katsunori Suginaka\n', '  Toshinobu Matsumiya\n', '\n', 'Funfest Mission Design\n', '  Masafumi Saito\n', '\n', 'Join Avenue Design\n', '  Teruyuki Shimoyamada\n', '\n', 'Pokemon Black and White Version Game Design\n', '  Shigeki Morimoto\n', '  Kenji Matsushima\n', '  Tetsuji Ohta\n', '  Shigeki Ohmori\n', '  Hiro Nakamura\n', '  Kazumasa Iwao\n', '  Yukiko Hozumi\n', '  Takeshi Kawachimaru\n', '  Tadashi Takahashi\n', '\n', 'Nintendo 3DS Link Design\n', '  Takao Unno\n', '  Masafumi Saito\n', '\n', 'Nintendo 3DS Link Programming\n', '  Yasunori Isari\n', '\n', 'Pokemon Black and White Version Wi-Fi Server Development\n', '  Takahiro Yamaguchi\n', '  Ryo Yamaguchi\n', '  Kazutomo Niwa\n', '  Takaaki Takeuchi\n', '  Mikihiro Ishikawa\n', '\n', 'Pokemon Global Link Design\n', '  Makiko Takahashi\n', '  Keiichi Yoshikawa\n', '  Shin Uwai\n', '  Basement Factory Productions\n', '\n', 'English Localization\n', '  Yasuhiro Usui\n', '  Mikiko Ryu\n', '  Satomi Honda\n', '\n', 'English Translation\n', '  Hisato Yamamori\n', '  Tim Hove\n', '  Sayuri Munday\n', '  David Numrich\n', '\n', 'English Editing\n', '  Kellyn Ballard\n', '  Blaise Selby\n', '  Hollie Beg\n', '\n', 'English Localization Support\n', '  Rey Perez\n', '  Antoin Johnson\n', '\n', 'NOA Localization Coordinators\n', '  Rie Fujiwara\n', '  Seth McMahill\n', '  Joel Simon\n', '\n', 'NOA Product Testing\n', '  Masayasu Nakata\n', '  Kyle Hudson\n', '  Eric M. Bush\n', '  Sean Egan\n', '  Ed Ridgeway\n', '  Teresa Lillygren\n', '  Leland Jones\n', '  Miyuki Matsunaga\n', '  Steven Kim\n', '  Allen Perez\n', '  Joshua Newman\n', '  Kindra Timmerwilke\n', '\n', 'NOE Localisation Management\n', '  Andy Fey\n', '  Micha챘l Hugot\n', '\n', 'NOE Localisation Producer\n', '  Jamie Grant\n', '\n', 'NOE QA Coordination\n', '  Luis Golbano\n', '  Jes첬s Gutierrez Cuadra\n', '  Patrick Thorenz\n', '\n', 'NOE Quality Assurance\n', '  Ben Howard-Hale\n', '  Chris Stewart\n', '  Ben Southam\n', '  Aatish Pattni\n', '\n', 'Localization\n', '  Teruki Murakawa\n', '  Akira Kinashi\n', '  Noriko Nakao\n', '  Hironori Ichibayashi\n', '  Shuhei Furukawa\n', '  Yuki Okada\n', '  Kei Ninomiya\n', '\n', 'Debug Management\n', '  Yuuki Tanikawa\n', '  Takahiro Kumasaka\n', '  Takuya Inoue\n', '  Motoki Nakajima\n', '  Akiko ohashi\n', '  Takeshi Tamura\n', '\n', 'Debug\n', '  Mario Club\n', '\n', 'World and Plot\n', '  Junichi Masuda\n', '\n', 'Special Thanks\n', '  Kenji Tominaga\n', '  Yuichiro Mori\n', '  Yoshio Tajiri\n', '  Teiko Sasaki\n', '  Emi Endo\n', '  Asami Sato\n', '  Nagaaki Fukase\n', '  Sachiko Hamano\n', '  Haruka Sunaga\n', '  Keisuke Takada\n', '  Hiroaki Tsuru\n', '  Kenjiro Ito\n', '  Mikiko ohashi\n', '  Tomotaka Komura\n', '  Atsushi Sugimoto\n', '  Susumu Fukunaga\n', '  Takato Utsunomiya\n', '  Oshito Miyahara\n', '  Taku Kawamoto\n', '  Gakuji Nomoto\n', '  Kanako Murata\n', '  Kochimi Takizawa\n', '  Mitsuyo Matsunaga\n', '  Sho Furutani\n', '  Takahiro Ohnishi\n', '  Yuichiro Tsumita\n', '  Osamu Fujita\n', '  Masayuki Soga\n', '  Yoko Nakayama\n', '  Kayo Nakata\n', '  Teruki Murakawa\n', '  Kaori Ando\n', '  Kotaro Hiromatsu\n', '  Shirohi Akune\n', '  Daisuke Komai\n', '  Toshio Mukai\n', '  Chiaki Takahara\n', '\n', 'English Version Artwork\n', '  Eric Medalle\n', "  Bridget O'Neill\n", '  Tina Sourinephoumy\n', '\n', 'Artwork\n', '  Kyomi Itani\n', '  Sachiko Nakamichi\n', '\n', 'Globalization Coordinators\n', '  Noriko Nakao\n', '  Hironori Ichibayashi\n', '  Shuhei Furukawa\n', '  Kei Ninomiya\n', '  Kenji Matsushima\n', '\n', 'Information Management\n', '  Toya Yoneda\n', '  Shiho Haraguchi\n', '  Yuuta Nakai\n', '  Yuri Sakurai\n', '\n', 'Coordinators\n', '  Shunsuke Kohori\n', '  Ayako Kajiwara\n', '  Akira Kinashi\n', '  Hideaki Araki\n', '  Yuki Okada\n', '\n', 'Producers\n', '  Junichi Masuda\n', '  Hitoshi Yamagami\n', '  Shusaku Egami\n', '\n', 'Executive Producers\n', '  Satoshi Tajiri\n', '  Satoru Iwata\n', '  Tsunekazu Ishihara']

후 정지. 음악은 안 멈췄네요.

**Comment by shs3182ym** [comment]
오류 내용이 뭔가요

**Comment by fsanchir** [comment]
오류는 안 나오나 저렇게 print 되는 걸 보니 뽑는 걸 실수하신 듯 합니다.

**Comment by shs3182ym** [comment]
저건 디버그한 후 코드를 제거 안 한 건 맞는데 멈추는 건 음악이랑 시작점이 맞게 44초 딜레이 넣어놨습니다

**Comment by fsanchir** [comment]
그럼 오류가 아니니 이슈 닫겠습니다.
